In [23]:
import numpy as np  

In [16]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])


In [17]:
sum_matrix = matrix1 + matrix2  

In [18]:
dot_product = np.dot(matrix1, matrix2)  


In [19]:
elementwise_mult = matrix1 * matrix2  

In [21]:
matrix_mult = matrix1 @ matrix2

In [22]:
print("Sum:\n", sum_matrix)
print("Dot Product:\n", dot_product)
print("Element-wise Multiplication:\n", elementwise_mult)
print("Matrix Multiplication (@ operator):\n", matrix_mult)


Sum:
 [[ 6  8]
 [10 12]]
Dot Product:
 [[19 22]
 [43 50]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication (@ operator):
 [[19 22]
 [43 50]]
